version: '3.7'
networks:
  Dani_edo:
    driver: bridge
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: edo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - edo-mariadb
    networks:
      - Dani_edo

  nginx:
    image: nginx:alpine
    container_name: edo-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "0.0.0.0:80:80"
      - "443:443"
    depends_on:
      - php
      # - phpmyadmin
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - Dani_edo

  edo-mariadb:
    image: mariadb:latest
    container_name: edo-mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "0.0.0.0:6969:3306"
    # env_file:
    #   - ./mysql/database.env
    environment:
      MYSQL_DATABASE: laravel_edo
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - Dani_edo

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: edo-phpmyadmin
  #   environment:
  #     PMA_USER: root
  #     PMA_PASSWORD: secret
  #     PMA_HOST: edo-mariadb
  #     PMA_PORT: 3306
  #   depends_on:
  #     - edo-mariadb
  #   ports:
  #     - '8080:80'
  #   networks:
  #     - Laravel

